// Generated by gencpp from file ImageProcess_Node/DetectRequest.msg
// DO NOT EDIT!


#ifndef IMAGEPROCESS_NODE_MESSAGE_DETECTREQUEST_H
#define IMAGEPROCESS_NODE_MESSAGE_DETECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ImageProcess_Node
{
template <class ContainerAllocator>
struct DetectRequest_
{
  typedef DetectRequest_<ContainerAllocator> Type;

  DetectRequest_()
    : roi_image(0.0)  {
    }
  DetectRequest_(const ContainerAllocator& _alloc)
    : roi_image(0.0)  {
  (void)_alloc;
    }



   typedef float _roi_image_type;
  _roi_image_type roi_image;




  typedef boost::shared_ptr< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DetectRequest_

typedef ::ImageProcess_Node::DetectRequest_<std::allocator<void> > DetectRequest;

typedef boost::shared_ptr< ::ImageProcess_Node::DetectRequest > DetectRequestPtr;
typedef boost::shared_ptr< ::ImageProcess_Node::DetectRequest const> DetectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ImageProcess_Node::DetectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ImageProcess_Node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0e029041da4e771f12f774b5957b1650";
  }

  static const char* value(const ::ImageProcess_Node::DetectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0e029041da4e771fULL;
  static const uint64_t static_value2 = 0x12f774b5957b1650ULL;
};

template<class ContainerAllocator>
struct DataType< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ImageProcess_Node/DetectRequest";
  }

  static const char* value(const ::ImageProcess_Node::DetectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roi_image\n\
";
  }

  static const char* value(const ::ImageProcess_Node::DetectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roi_image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ImageProcess_Node::DetectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ImageProcess_Node::DetectRequest_<ContainerAllocator>& v)
  {
    s << indent << "roi_image: ";
    Printer<float>::stream(s, indent + "  ", v.roi_image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGEPROCESS_NODE_MESSAGE_DETECTREQUEST_H
