// Generated by gencpp from file ImageProcess_Node/Detect.msg
// DO NOT EDIT!


#ifndef IMAGEPROCESS_NODE_MESSAGE_DETECT_H
#define IMAGEPROCESS_NODE_MESSAGE_DETECT_H

#include <ros/service_traits.h>


#include <ImageProcess_Node/DetectRequest.h>
#include <ImageProcess_Node/DetectResponse.h>


namespace ImageProcess_Node
{

struct Detect
{

typedef DetectRequest Request;
typedef DetectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detect
} // namespace ImageProcess_Node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ImageProcess_Node::Detect > {
  static const char* value()
  {
    return "c5cdbbf937a2b7afdb40f16147414b23";
  }

  static const char* value(const ::ImageProcess_Node::Detect&) { return value(); }
};

template<>
struct DataType< ::ImageProcess_Node::Detect > {
  static const char* value()
  {
    return "ImageProcess_Node/Detect";
  }

  static const char* value(const ::ImageProcess_Node::Detect&) { return value(); }
};


// service_traits::MD5Sum< ::ImageProcess_Node::DetectRequest> should match 
// service_traits::MD5Sum< ::ImageProcess_Node::Detect > 
template<>
struct MD5Sum< ::ImageProcess_Node::DetectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ImageProcess_Node::Detect >::value();
  }
  static const char* value(const ::ImageProcess_Node::DetectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ImageProcess_Node::DetectRequest> should match 
// service_traits::DataType< ::ImageProcess_Node::Detect > 
template<>
struct DataType< ::ImageProcess_Node::DetectRequest>
{
  static const char* value()
  {
    return DataType< ::ImageProcess_Node::Detect >::value();
  }
  static const char* value(const ::ImageProcess_Node::DetectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ImageProcess_Node::DetectResponse> should match 
// service_traits::MD5Sum< ::ImageProcess_Node::Detect > 
template<>
struct MD5Sum< ::ImageProcess_Node::DetectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ImageProcess_Node::Detect >::value();
  }
  static const char* value(const ::ImageProcess_Node::DetectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ImageProcess_Node::DetectResponse> should match 
// service_traits::DataType< ::ImageProcess_Node::Detect > 
template<>
struct DataType< ::ImageProcess_Node::DetectResponse>
{
  static const char* value()
  {
    return DataType< ::ImageProcess_Node::Detect >::value();
  }
  static const char* value(const ::ImageProcess_Node::DetectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMAGEPROCESS_NODE_MESSAGE_DETECT_H
