// Generated by gencpp from file ImageProcess_Node/DetectLaneResult.msg
// DO NOT EDIT!


#ifndef IMAGEPROCESS_NODE_MESSAGE_DETECTLANERESULT_H
#define IMAGEPROCESS_NODE_MESSAGE_DETECTLANERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ImageProcess_Node
{
template <class ContainerAllocator>
struct DetectLaneResult_
{
  typedef DetectLaneResult_<ContainerAllocator> Type;

  DetectLaneResult_()
    : result()  {
    }
  DetectLaneResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> const> ConstPtr;

}; // struct DetectLaneResult_

typedef ::ImageProcess_Node::DetectLaneResult_<std::allocator<void> > DetectLaneResult;

typedef boost::shared_ptr< ::ImageProcess_Node::DetectLaneResult > DetectLaneResultPtr;
typedef boost::shared_ptr< ::ImageProcess_Node::DetectLaneResult const> DetectLaneResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ImageProcess_Node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'ImageProcess_Node': ['/home/seopaul/Auto-Mobile-Robot/devel/share/ImageProcess_Node/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ImageProcess_Node/DetectLaneResult";
  }

  static const char* value(const ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Define the result\n\
string result\n\
";
  }

  static const char* value(const ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectLaneResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ImageProcess_Node::DetectLaneResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGEPROCESS_NODE_MESSAGE_DETECTLANERESULT_H
