; Auto-generated. Do not edit!


(cl:in-package ImageProcessing_Node-msg)


;//! \htmlinclude DetectSignFeedback.msg.html

(cl:defclass <DetectSignFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:string
    :initform "")
   (detect_num
    :reader detect_num
    :initarg :detect_num
    :type cl:integer
    :initform 0))
)

(cl:defclass DetectSignFeedback (<DetectSignFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DetectSignFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DetectSignFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ImageProcessing_Node-msg:<DetectSignFeedback> is deprecated: use ImageProcessing_Node-msg:DetectSignFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <DetectSignFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ImageProcessing_Node-msg:status-val is deprecated.  Use ImageProcessing_Node-msg:status instead.")
  (status m))

(cl:ensure-generic-function 'detect_num-val :lambda-list '(m))
(cl:defmethod detect_num-val ((m <DetectSignFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ImageProcessing_Node-msg:detect_num-val is deprecated.  Use ImageProcessing_Node-msg:detect_num instead.")
  (detect_num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DetectSignFeedback>) ostream)
  "Serializes a message object of type '<DetectSignFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'detect_num)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'detect_num)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'detect_num)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'detect_num)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DetectSignFeedback>) istream)
  "Deserializes a message object of type '<DetectSignFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'detect_num)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'detect_num)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'detect_num)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'detect_num)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DetectSignFeedback>)))
  "Returns string type for a message object of type '<DetectSignFeedback>"
  "ImageProcessing_Node/DetectSignFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DetectSignFeedback)))
  "Returns string type for a message object of type 'DetectSignFeedback"
  "ImageProcessing_Node/DetectSignFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DetectSignFeedback>)))
  "Returns md5sum for a message object of type '<DetectSignFeedback>"
  "b1080d0cf5321ed4c85f905931903479")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DetectSignFeedback)))
  "Returns md5sum for a message object of type 'DetectSignFeedback"
  "b1080d0cf5321ed4c85f905931903479")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DetectSignFeedback>)))
  "Returns full string definition for message of type '<DetectSignFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string status~%uint32 detect_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DetectSignFeedback)))
  "Returns full string definition for message of type 'DetectSignFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string status~%uint32 detect_num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DetectSignFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'status))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DetectSignFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DetectSignFeedback
    (cl:cons ':status (status msg))
    (cl:cons ':detect_num (detect_num msg))
))
