; Auto-generated. Do not edit!


(cl:in-package ImageProcessing_Node-msg)


;//! \htmlinclude DetectLaneResult.msg.html

(cl:defclass <DetectLaneResult> (roslisp-msg-protocol:ros-message)
  ((error
    :reader error
    :initarg :error
    :type cl:float
    :initform 0.0))
)

(cl:defclass DetectLaneResult (<DetectLaneResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DetectLaneResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DetectLaneResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ImageProcessing_Node-msg:<DetectLaneResult> is deprecated: use ImageProcessing_Node-msg:DetectLaneResult instead.")))

(cl:ensure-generic-function 'error-val :lambda-list '(m))
(cl:defmethod error-val ((m <DetectLaneResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ImageProcessing_Node-msg:error-val is deprecated.  Use ImageProcessing_Node-msg:error instead.")
  (error m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DetectLaneResult>) ostream)
  "Serializes a message object of type '<DetectLaneResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'error))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DetectLaneResult>) istream)
  "Deserializes a message object of type '<DetectLaneResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'error) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DetectLaneResult>)))
  "Returns string type for a message object of type '<DetectLaneResult>"
  "ImageProcessing_Node/DetectLaneResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DetectLaneResult)))
  "Returns string type for a message object of type 'DetectLaneResult"
  "ImageProcessing_Node/DetectLaneResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DetectLaneResult>)))
  "Returns md5sum for a message object of type '<DetectLaneResult>"
  "417c68e466c6131d4fed652219a9ccb7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DetectLaneResult)))
  "Returns md5sum for a message object of type 'DetectLaneResult"
  "417c68e466c6131d4fed652219a9ccb7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DetectLaneResult>)))
  "Returns full string definition for message of type '<DetectLaneResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DetectLaneResult)))
  "Returns full string definition for message of type 'DetectLaneResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 error~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DetectLaneResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DetectLaneResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DetectLaneResult
    (cl:cons ':error (error msg))
))
