// Generated by gencpp from file Control_Node/Mission.msg
// DO NOT EDIT!


#ifndef CONTROL_NODE_MESSAGE_MISSION_H
#define CONTROL_NODE_MESSAGE_MISSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Control_Node
{
template <class ContainerAllocator>
struct Mission_
{
  typedef Mission_<ContainerAllocator> Type;

  Mission_()
    : traffic(false)
    , parking(false)
    , crossbar(false)
    , tunnel(false)  {
    }
  Mission_(const ContainerAllocator& _alloc)
    : traffic(false)
    , parking(false)
    , crossbar(false)
    , tunnel(false)  {
  (void)_alloc;
    }



   typedef uint8_t _traffic_type;
  _traffic_type traffic;

   typedef uint8_t _parking_type;
  _parking_type parking;

   typedef uint8_t _crossbar_type;
  _crossbar_type crossbar;

   typedef uint8_t _tunnel_type;
  _tunnel_type tunnel;





  typedef boost::shared_ptr< ::Control_Node::Mission_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Control_Node::Mission_<ContainerAllocator> const> ConstPtr;

}; // struct Mission_

typedef ::Control_Node::Mission_<std::allocator<void> > Mission;

typedef boost::shared_ptr< ::Control_Node::Mission > MissionPtr;
typedef boost::shared_ptr< ::Control_Node::Mission const> MissionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Control_Node::Mission_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Control_Node::Mission_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Control_Node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'Control_Node': ['/home/seopaul/Auto-Mobile-Robot/src/Control_Node/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Control_Node::Mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Control_Node::Mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Control_Node::Mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Control_Node::Mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Control_Node::Mission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Control_Node::Mission_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Control_Node::Mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "132b675c11a085c243deb3519223ef08";
  }

  static const char* value(const ::Control_Node::Mission_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x132b675c11a085c2ULL;
  static const uint64_t static_value2 = 0x43deb3519223ef08ULL;
};

template<class ContainerAllocator>
struct DataType< ::Control_Node::Mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Control_Node/Mission";
  }

  static const char* value(const ::Control_Node::Mission_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Control_Node::Mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool traffic\n\
bool parking\n\
bool crossbar\n\
bool tunnel\n\
";
  }

  static const char* value(const ::Control_Node::Mission_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Control_Node::Mission_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traffic);
      stream.next(m.parking);
      stream.next(m.crossbar);
      stream.next(m.tunnel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Mission_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Control_Node::Mission_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Control_Node::Mission_<ContainerAllocator>& v)
  {
    s << indent << "traffic: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.traffic);
    s << indent << "parking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.parking);
    s << indent << "crossbar: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.crossbar);
    s << indent << "tunnel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tunnel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_NODE_MESSAGE_MISSION_H
