// Generated by gencpp from file ImageProcessing_Node/DetectLane.msg
// DO NOT EDIT!


#ifndef IMAGEPROCESSING_NODE_MESSAGE_DETECTLANE_H
#define IMAGEPROCESSING_NODE_MESSAGE_DETECTLANE_H

#include <ros/service_traits.h>


#include <ImageProcessing_Node/DetectLaneRequest.h>
#include <ImageProcessing_Node/DetectLaneResponse.h>


namespace ImageProcessing_Node
{

struct DetectLane
{

typedef DetectLaneRequest Request;
typedef DetectLaneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectLane
} // namespace ImageProcessing_Node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ImageProcessing_Node::DetectLane > {
  static const char* value()
  {
    return "a6e07a703491622fa69b198031d85522";
  }

  static const char* value(const ::ImageProcessing_Node::DetectLane&) { return value(); }
};

template<>
struct DataType< ::ImageProcessing_Node::DetectLane > {
  static const char* value()
  {
    return "ImageProcessing_Node/DetectLane";
  }

  static const char* value(const ::ImageProcessing_Node::DetectLane&) { return value(); }
};


// service_traits::MD5Sum< ::ImageProcessing_Node::DetectLaneRequest> should match 
// service_traits::MD5Sum< ::ImageProcessing_Node::DetectLane > 
template<>
struct MD5Sum< ::ImageProcessing_Node::DetectLaneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ImageProcessing_Node::DetectLane >::value();
  }
  static const char* value(const ::ImageProcessing_Node::DetectLaneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ImageProcessing_Node::DetectLaneRequest> should match 
// service_traits::DataType< ::ImageProcessing_Node::DetectLane > 
template<>
struct DataType< ::ImageProcessing_Node::DetectLaneRequest>
{
  static const char* value()
  {
    return DataType< ::ImageProcessing_Node::DetectLane >::value();
  }
  static const char* value(const ::ImageProcessing_Node::DetectLaneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ImageProcessing_Node::DetectLaneResponse> should match 
// service_traits::MD5Sum< ::ImageProcessing_Node::DetectLane > 
template<>
struct MD5Sum< ::ImageProcessing_Node::DetectLaneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ImageProcessing_Node::DetectLane >::value();
  }
  static const char* value(const ::ImageProcessing_Node::DetectLaneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ImageProcessing_Node::DetectLaneResponse> should match 
// service_traits::DataType< ::ImageProcessing_Node::DetectLane > 
template<>
struct DataType< ::ImageProcessing_Node::DetectLaneResponse>
{
  static const char* value()
  {
    return DataType< ::ImageProcessing_Node::DetectLane >::value();
  }
  static const char* value(const ::ImageProcessing_Node::DetectLaneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMAGEPROCESSING_NODE_MESSAGE_DETECTLANE_H
