// Generated by gencpp from file ImageProcessing_Node/Detect.msg
// DO NOT EDIT!


#ifndef IMAGEPROCESSING_NODE_MESSAGE_DETECT_H
#define IMAGEPROCESSING_NODE_MESSAGE_DETECT_H

#include <ros/service_traits.h>


#include <ImageProcessing_Node/DetectRequest.h>
#include <ImageProcessing_Node/DetectResponse.h>


namespace ImageProcessing_Node
{

struct Detect
{

typedef DetectRequest Request;
typedef DetectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detect
} // namespace ImageProcessing_Node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ImageProcessing_Node::Detect > {
  static const char* value()
  {
    return "a3926dcdd8f922bd0ad49b8c9d565283";
  }

  static const char* value(const ::ImageProcessing_Node::Detect&) { return value(); }
};

template<>
struct DataType< ::ImageProcessing_Node::Detect > {
  static const char* value()
  {
    return "ImageProcessing_Node/Detect";
  }

  static const char* value(const ::ImageProcessing_Node::Detect&) { return value(); }
};


// service_traits::MD5Sum< ::ImageProcessing_Node::DetectRequest> should match 
// service_traits::MD5Sum< ::ImageProcessing_Node::Detect > 
template<>
struct MD5Sum< ::ImageProcessing_Node::DetectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ImageProcessing_Node::Detect >::value();
  }
  static const char* value(const ::ImageProcessing_Node::DetectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ImageProcessing_Node::DetectRequest> should match 
// service_traits::DataType< ::ImageProcessing_Node::Detect > 
template<>
struct DataType< ::ImageProcessing_Node::DetectRequest>
{
  static const char* value()
  {
    return DataType< ::ImageProcessing_Node::Detect >::value();
  }
  static const char* value(const ::ImageProcessing_Node::DetectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ImageProcessing_Node::DetectResponse> should match 
// service_traits::MD5Sum< ::ImageProcessing_Node::Detect > 
template<>
struct MD5Sum< ::ImageProcessing_Node::DetectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ImageProcessing_Node::Detect >::value();
  }
  static const char* value(const ::ImageProcessing_Node::DetectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ImageProcessing_Node::DetectResponse> should match 
// service_traits::DataType< ::ImageProcessing_Node::Detect > 
template<>
struct DataType< ::ImageProcessing_Node::DetectResponse>
{
  static const char* value()
  {
    return DataType< ::ImageProcessing_Node::Detect >::value();
  }
  static const char* value(const ::ImageProcessing_Node::DetectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IMAGEPROCESSING_NODE_MESSAGE_DETECT_H
