// Generated by gencpp from file ImageProcessing_Node/DetectLaneFeedback.msg
// DO NOT EDIT!


#ifndef IMAGEPROCESSING_NODE_MESSAGE_DETECTLANEFEEDBACK_H
#define IMAGEPROCESSING_NODE_MESSAGE_DETECTLANEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ImageProcessing_Node
{
template <class ContainerAllocator>
struct DetectLaneFeedback_
{
  typedef DetectLaneFeedback_<ContainerAllocator> Type;

  DetectLaneFeedback_()
    : status()  {
    }
  DetectLaneFeedback_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DetectLaneFeedback_

typedef ::ImageProcessing_Node::DetectLaneFeedback_<std::allocator<void> > DetectLaneFeedback;

typedef boost::shared_ptr< ::ImageProcessing_Node::DetectLaneFeedback > DetectLaneFeedbackPtr;
typedef boost::shared_ptr< ::ImageProcessing_Node::DetectLaneFeedback const> DetectLaneFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ImageProcessing_Node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'ImageProcessing_Node': ['/home/seopaul/Auto-Mobile-Robot/devel/share/ImageProcessing_Node/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fe5af303955c287688e7347e9b00278";
  }

  static const char* value(const ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fe5af303955c287ULL;
  static const uint64_t static_value2 = 0x688e7347e9b00278ULL;
};

template<class ContainerAllocator>
struct DataType< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ImageProcessing_Node/DetectLaneFeedback";
  }

  static const char* value(const ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string status\n\
";
  }

  static const char* value(const ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectLaneFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ImageProcessing_Node::DetectLaneFeedback_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGEPROCESSING_NODE_MESSAGE_DETECTLANEFEEDBACK_H
