// Generated by gencpp from file stack_image_node/SaveRequest.msg
// DO NOT EDIT!


#ifndef STACK_IMAGE_NODE_MESSAGE_SAVEREQUEST_H
#define STACK_IMAGE_NODE_MESSAGE_SAVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stack_image_node
{
template <class ContainerAllocator>
struct SaveRequest_
{
  typedef SaveRequest_<ContainerAllocator> Type;

  SaveRequest_()
    : flag_message()  {
    }
  SaveRequest_(const ContainerAllocator& _alloc)
    : flag_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _flag_message_type;
  _flag_message_type flag_message;




  typedef boost::shared_ptr< ::stack_image_node::SaveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stack_image_node::SaveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveRequest_

typedef ::stack_image_node::SaveRequest_<std::allocator<void> > SaveRequest;

typedef boost::shared_ptr< ::stack_image_node::SaveRequest > SaveRequestPtr;
typedef boost::shared_ptr< ::stack_image_node::SaveRequest const> SaveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stack_image_node::SaveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stack_image_node::SaveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace stack_image_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::stack_image_node::SaveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stack_image_node::SaveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stack_image_node::SaveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stack_image_node::SaveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stack_image_node::SaveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stack_image_node::SaveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stack_image_node::SaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14fdb931223464f74c4be57e81a7ef44";
  }

  static const char* value(const ::stack_image_node::SaveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14fdb931223464f7ULL;
  static const uint64_t static_value2 = 0x4c4be57e81a7ef44ULL;
};

template<class ContainerAllocator>
struct DataType< ::stack_image_node::SaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stack_image_node/SaveRequest";
  }

  static const char* value(const ::stack_image_node::SaveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stack_image_node::SaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string flag_message\n\
";
  }

  static const char* value(const ::stack_image_node::SaveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stack_image_node::SaveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stack_image_node::SaveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stack_image_node::SaveRequest_<ContainerAllocator>& v)
  {
    s << indent << "flag_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.flag_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STACK_IMAGE_NODE_MESSAGE_SAVEREQUEST_H
